"""
Recommendation models.

These models represent intelligent recommendations generated
from dataset inspection results.

Recommendations are rule-based and explain WHY an action is
suggested before any modification is performed.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import Field

from cleaner.models.base import BaseCleanerModel, ColumnReference


class RecommendationCategory(StrEnum):
    """
    High-level recommendation categories.
    """

    MISSING_VALUES = "missing_values"
    DUPLICATES = "duplicates"
    DATA_TYPES = "data_types"
    MEMORY = "memory"
    OUTLIERS = "outliers"
    FEATURE_ENGINEERING = "feature_engineering"
    FEATURE_SELECTION = "feature_selection"
    ENCODING = "encoding"
    SCALING = "scaling"
    CLEANING = "cleaning"
    GENERAL = "general"


class RecommendationPriority(StrEnum):
    """
    Recommendation importance.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RecommendationAction(StrEnum):
    """
    Supported actions.

    The engine converts these actions into executable
    preprocessing steps later.
    """

    DROP_COLUMN = "drop_column"
    DROP_ROWS = "drop_rows"
    FILL_MEAN = "fill_mean"
    FILL_MEDIAN = "fill_median"
    FILL_MODE = "fill_mode"
    FILL_CONSTANT = "fill_constant"
    CONVERT_TYPE = "convert_type"
    REMOVE_DUPLICATES = "remove_duplicates"
    OPTIMIZE_MEMORY = "optimize_memory"
    ENCODE = "encode"
    SCALE = "scale"
    NORMALIZE = "normalize"
    CREATE_FEATURE = "create_feature"
    KEEP = "keep"
    CUSTOM = "custom"


class RecommendationReason(BaseCleanerModel):
    """
    Human-readable explanation.

    Example
    -------
    Missing percentage exceeds threshold.

    Median is preferred because
    the distribution is skewed.
    """

    title: str = Field(
        min_length=1,
    )

    explanation: str = Field(
        min_length=1,
    )


class RecommendationImpact(BaseCleanerModel):
    """
    Estimated impact.

    Used for UI/report generation.
    """

    memory_change_mb: float = 0.0

    row_change: int = 0

    column_change: int = 0

    quality_score_delta: float = 0.0


class Recommendation(BaseCleanerModel):
    """
    Single recommendation generated by the engine.
    """

    title: str

    description: str

    category: RecommendationCategory

    priority: RecommendationPriority

    action: RecommendationAction

    column: ColumnReference | None = None

    reason: RecommendationReason

    impact: RecommendationImpact

    confidence: float = Field(
        ge=0,
        le=1,
        description="Confidence score between 0 and 1.",
    )

    automatic: bool = Field(
        default=False,
        description="Whether this action can be safely automated.",
    )

    enabled: bool = Field(
        default=True,
        description="Whether the recommendation is active.",
    )


class RecommendationGroup(BaseCleanerModel):
    """
    Groups recommendations together.

    Example
    -------
    Missing Values

        - Fill Age
        - Fill Salary
        - Drop Cabin
    """

    category: RecommendationCategory

    recommendations: list[Recommendation] = Field(
        default_factory=list,
    )


class RecommendationSummary(BaseCleanerModel):
    """
    Summary statistics.
    """

    total: int = Field(
        ge=0,
    )

    critical: int = Field(
        ge=0,
    )

    high: int = Field(
        ge=0,
    )

    medium: int = Field(
        ge=0,
    )

    low: int = Field(
        ge=0,
    )


class RecommendationResult(BaseCleanerModel):
    """
    Final recommendation output returned by the engine.
    """

    summary: RecommendationSummary

    groups: list[RecommendationGroup] = Field(
        default_factory=list,
    )

    recommendations: list[Recommendation] = Field(
        default_factory=list,
    )


__all__ = [
    "RecommendationCategory",
    "RecommendationPriority",
    "RecommendationAction",
    "RecommendationReason",
    "RecommendationImpact",
    "Recommendation",
    "RecommendationGroup",
    "RecommendationSummary",
    "RecommendationResult",
]
