"""
Report Models

Defines the final report structure generated by Cleaner after
dataset inspection. This model aggregates inspection results,
recommendations, execution metadata, and overall dataset health.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import Field

from .base import BaseCleanerModel
from .inspection import InspectionResult
from .recommendations import Recommendation


class ReportSummary(BaseCleanerModel):
    """
    High-level summary statistics.
    """

    total_rows: int = Field(..., ge=0)
    total_columns: int = Field(..., ge=0)

    duplicate_rows: int = Field(default=0, ge=0)
    missing_cells: int = Field(default=0, ge=0)

    memory_usage_bytes: int = Field(default=0, ge=0)

    health_score: float = Field(
        default=100.0,
        ge=0.0,
        le=100.0,
        description="Overall dataset health score.",
    )


class ExecutionMetadata(BaseCleanerModel):
    """
    Runtime information.
    """

    started_at: datetime
    finished_at: datetime

    execution_time_seconds: float = Field(
        ...,
        ge=0,
    )

    cleaner_version: str


class CleanerReport(BaseCleanerModel):
    """
    Final report returned by Cleaner.

    This is the primary object exposed to users.
    """

    summary: ReportSummary

    inspections: list[InspectionResult] = Field(default_factory=list)

    recommendations: list[Recommendation] = Field(default_factory=list)

    metadata: ExecutionMetadata

    @property
    def total_issues(self) -> int:
        """
        Number of detected inspection issues.
        """
        return len(self.inspections)

    @property
    def total_recommendations(self) -> int:
        """
        Number of generated recommendations.
        """
        return len(self.recommendations)

    @property
    def critical_recommendations(self) -> int:
        """
        Count CRITICAL recommendations.
        """
        return sum(r.priority.value == "critical" for r in self.recommendations)

    @property
    def warning_recommendations(self) -> int:
        """
        Count WARNING recommendations.
        """
        return sum(r.priority.value == "warning" for r in self.recommendations)

    @property
    def info_recommendations(self) -> int:
        """
        Count INFO recommendations.
        """
        return sum(r.priority.value == "info" for r in self.recommendations)
